version: '3.8'
name: finance-tracking
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgresql://postgres:pWlWNBMMKqULMKdSegJlnHZiphBaFEti@monorail.proxy.rlwy.net:14559/railway
    ports:
      - 8000:8000
    volumes:
      - ./:/app