version: '3.8'
name: finance-tracking
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgresql://postgres:qEymZTkCXtNDAGGRTwfbLjsJTMPtPwrR@viaduct.proxy.rlwy.net:24244/railway
    ports:
      - 8080:8080
    volumes:
      - ./:/app